### ISSUE TITLE
utm_geo() routine needs corrections

### ISSUE THREAD

**Issue by danielpeter** [SCECcode/cca#1]
Please note that your utm_geo() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: utm_geo.f90

line 95:
https://github.com/SCECcode/CCA/blob/71cd8f8ea6fafbc890ceed1c90d7fca693f4ffae/src/utm_geo.f90#L95

wrong: `f3=15.d0*e4/256.d0*45.d0*e6/1024.d0`
correct would be: `f3=15.d0*e4/256.d0 + 45.d0*e6/1024.d0`

line 160
https://github.com/SCECcode/CCA/blob/71cd8f8ea6fafbc890ceed1c90d7fca693f4ffae/src/utm_geo.f90#L160

wrong:  `f3=5.d0*3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`
correct would be:  `f3=5.d0 + 3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395

line 95 mistake/correction: see page 61, eq. 3-21 for M
line 160 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by baagaard-usgs** [comment]
The source code `cca.c` creates projection objects using Proj but never uses them. These should be used instead of `utm_geo.f`. Using the projection objects also eliminates the need for a Fortran compiler.

**Comment by baagaard-usgs** [comment]
What software was used to georeference the model when it was developed? Was it the utm_geo() routine with errors? with correct parameters? In other words, in switching to Proj which provides accurate conversions between UTM and geographic coordinates, does the model georeferencing need to be updated?
